# -*- coding: utf-8 -*-
"""task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Qxp6_arzWsCr_AaCQe-kA95I19BZ7WJ
"""

def calculate_grade(marks):
  if marks>=90 and marks<=100:

    print("A")
  elif marks>=75 and marks<90:

    print("B")
  elif marks>=60 and marks<75:
    print("C")
  elif marks>=0 and marks<60:
    print("fail")
  else:
    print("invalide")

a=int(input("enter the marks\t"))
calculate_grade(a)



def validate_password(password):
  if len(password)>=8:


    digit=False
    alpha=False
    for a in password:
      if a.isdigit():
        digit=True
      if a.isupper():
        alpha=True
    if digit==True and alpha==True:
      print("valid password")
    else:
      print("invalid password")

  else:

    print("At least 8 characters")

a=input("enter an  password\t")
validate_password(a)

